{application,mantra,
             [{description,"Distributed Chat Backend Service."},
              {vsn,"0.1.0"},
              {registered,[]},
              {applications,[kernel,stdlib]},
              {mod,{mantra,[]}},
              {env,[]},
              {modules,[client,command_parser,connection,gateway_sup,listener,
                        mantra,mantra_sup,registry_sup,room,room_manager,
                        room_registry,room_sup,session_registry,user_session,
                        user_session_sup]},
              {licenses,["Apache-2.0"]},
              {links,[]}]}.
